DELETE http://157.245.201.127:3001/api/jobs/2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE2NTkxNjMyMDAsImV4cCI6MTY1OTIwNjQwMH0.uuH88D-XV3aF9nBeQMRZn35CRp3nlYrqYTwVfOppRXg
